# -*- coding: utf-8 -*-
"""Untitled88.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RN0fgINjSvGrx_0OVWQYKARezOmqm_q
"""

!pip install imageio-ffmpeg

# Contoh penggunaan
gif_url = "https://i0.wp.com/education.civitai.com/wp-content/uploads/2023/11/animatediff_gif_inner_reflections_AI.gif?resize=600%2C338&ssl=1"

import requests
import imageio
import os

def download_gif(url, save_path):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raises an HTTPError for bad responses

        with open(save_path, 'wb') as file:
            file.write(response.content)

        print(f"File downloaded successfully: {save_path}")
    except requests.exceptions.RequestException as e:
        print(f"Error downloading file: {e}")

def convert_gif_to_mp4(gif_path, mp4_path, fps=10):
    try:
        with imageio.get_reader(gif_path) as reader, imageio.get_writer(mp4_path, fps=fps) as writer:
            for frame in reader:
                writer.append_data(frame)

        print(f"Conversion successful: {mp4_path}")
    except Exception as e:
        print(f"Error converting GIF to MP4: {e}")

# Membuat nama file baru dengan nomor urut
counter = 1
base_path = "video-download"
gif_extension = ".gif"
mp4_extension = ".mp4"

while os.path.exists(f"{base_path}{counter}{gif_extension}"):
    counter += 1

downloaded_gif_path = f"{base_path}{counter}{gif_extension}"
output_mp4_path = f"{base_path}{counter}{mp4_extension}"

download_gif(gif_url, downloaded_gif_path)
convert_gif_to_mp4(downloaded_gif_path, output_mp4_path)
